name: Deploy EC2 Instance

on:
    push:
     branches:
     - main

jobs:
  aws-setup:
    runs-on: ubuntu-latest
    outputs:
      aws-configured: ${{ steps.configure-aws.outputs.aws-configured }}

    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Configurar credenciales AWS
       id: configure-aws
       uses: aws-actions/configure-aws-credentials@v2
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_SECRET_REGION }}


  create-instance:
    runs-on: ubuntu-latest
    needs: aws-setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        id: configure-aws
        uses: aws-actions/configure-aws-credentials@v2
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_SECRET_REGION }}
      
      - name: Crear instancia EC2
        run: |
          aws ec2 run-instances \
          --image-id ami-088d38b423bff245f \
          --count 1 \
          --instance-type t2.micro \
          --key-name desafio_modulo5 \
          --security-group-ids ${{ vars.SECURITY_GROUP_ID }} \
          --subnet-id ${{ vars.SUBNET_ID }} \
          --associate-public-ip-address \
          --region ${{ secrets.AWS_SECRET_REGION }}